server:
  port: ${peer1.server.port}

spring:
  profiles: peer1
  datasource:
    url: jdbc:mysql://${spring.mysql.host}:${spring.mysql.port}/${spring.mysql.database}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${spring.mysql.username}
    password: ${spring.mysql.password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${peer1.eureka.client.serviceUrl.defaultZone}

tx-lcn:
  manager:
    host: ${peer1.tx-lcn.manager.host}
    port: ${peer1.tx-lcn.manager.port}
