eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zxkjgkpt/config-resources/
          searchPaths: '{application}-config'
          username: 568777035@qq.com
          password: zjs568777035
          basedir: /tmp/config-resources
      label: master
