eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.instance.hostname@:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: @config.server.git.uri@
          searchPaths: '{application}-config'
          username: @config.server.git.username@
          password: @config.server.git.password@
          basedir: @config.server.git.basedir@
      label: master
